export const servicesData = [
  {
    title: "Olieskift",
    slug: "olieskift",
    price: "fra 599 kr.",
    duration: "30-60 min",
    description: "Vi udfører olieskift på alle bilmærker og modeller. Inkluderer udskiftning af oliefilter og kontrol af olieniveau. Vi bruger olie af den type og viskositet, der er anbefalet til din bil.",
    includes: ["Aftapning af gammel olie", "Nyt oliefilter", "Påfyldning af godkendt motorolie", "Kontrol og nulstilling af service-indikator", "Generel visuel kontrol"],
  },
  {
    title: "Bremseskift",
    slug: "bremseskift",
    price: "fra 899 kr.",
    duration: "60-120 min",
    description: "Professionel udskiftning af bremseklodser og/eller skiver. Vi arbejder med alle bilmærker og bruger originale eller godkendte kvalitetsdele.",
    includes: ["Kontrol af bremsebelægning", "Udskiftning af klodser/skiver efter behov", "Rengøring og smøring", "Prøvekørsel og kontrol"],
  },
  {
    title: "Synsforberedelse",
    slug: "synsforberedelse",
    price: "fra 499 kr.",
    duration: "45-90 min",
    description: "Vi gennemgår din bil grundigt inden syn og udbedrer eventuelle fejl, så du er sikker på at bestå.",
    includes: ["Komplet synspunkter-gennemgang", "Lys og signalgivere", "Bremser og styretøj", "Dæk og fælge", "Udstødning og emissioner"],
  },
  {
    title: "Dækskift",
    slug: "daekskift",
    price: "fra 399 kr.",
    duration: "30-45 min",
    description: "Hurtig og professionel dækmontage med balancering. Vi tilbyder også sæsonopbevaring af dine ekstra dæk.",
    includes: ["Af- og påmontering", "Balancering", "Dæktryks-kontrol", "Tilbud om opbevaring"],
  },
  {
    title: "Klimaservice",
    slug: "klimaservice",
    price: "fra 699 kr.",
    duration: "60 min",
    description: "Opfyldning og kontrol af klimaanlæg. Vi tjekker for lækager og sikrer, at dit anlæg fungerer optimalt.",
    includes: ["Afpresning og kontrol", "Opfyldning af kølemiddel", "Tilsætning af olie", "Kabinefilter kontrol"],
  },
  {
    title: "Fejldiagnose",
    slug: "fejldiagnose",
    price: "fra 349 kr.",
    duration: "30-60 min",
    description: "Med moderne diagnostikudstyr finder vi fejlen i din bil hurtigt og præcist. Fejlkoder læses og fejlfindes.",
    includes: ["Komputer-diagnostik", "Fejlkode-analyse", "Rapport med fund", "Tilbud på udbedring"],
  },
  {
    title: "El-bil service",
    slug: "el-bil-service",
    price: "Kontakt os",
    duration: "Varierer",
    description: "Vi er certificeret til service og vedligeholdelse af el-biler og plug-in hybrider.",
    includes: ["Batteri-inspektion", "Softwareopdatering", "Ladeport kontrol", "Chassis og bremser"],
  },
  {
    title: "Stor service",
    slug: "stor-service",
    price: "fra 1.499 kr.",
    duration: "2-3 timer",
    description: "En komplet gennemgang af alle vitale komponenter i din bil. Anbefales hvert 2. år eller 30.000 km.",
    includes: ["Olieskift", "Alle filtre", "Tændingsanlæg", "Bremser", "Væskeniveauer", "Over 30 kontrolpunkter"],
  },
];
